export { CellActionExecutor, UIBridge } from './CellActionExecutor';
export { RewardSystem } from './RewardSystem';
export { ProgressManager } from './ProgressManager';
export { SaveStorage } from './storage/SaveStorage';
export { LevelAssignmentEngine } from './LevelAssignmentEngine';
export { MapFlipEngine } from './mapFlipEngine';
export type { FlipResult } from './mapFlipEngine';
export { BattleIntegration } from './battleIntegration';
export type { ICoreResources, IEquipmentBonus, IItemDrop, IBattlePlayerState, BattleResources, BattleRewards, BattleSetup, BattleResult, GameOverCheck } from './battleIntegration';
export { TowerGameStateManager } from './towerGameState';
export type { TowerGameState } from './towerGameState';
export { DynamicMechanicsEngine } from './dynamicMechanics';
export type { IMobilityConfig, IBoundaryFlexConfig, IProbabilityConfig, IEnrichedTopology } from './dynamicMechanics';
export { CurvedPathEngine } from './curvedPathEngine';
export type { PathPoint } from './curvedPathEngine';
export { PlayerPieceManager } from './playerPiece';
export type { TrailPoint, PlayerPieceState } from './playerPiece';
export { TurnManager } from './turnManager';
export type { TurnPhase, TurnContext, TurnManagerOptions } from './turnManager';
export { BattleOrchestrator } from './battleOrchestrator';
export type { BattlePhase, BattleOrchestratorState } from './battleOrchestrator';
export { TowerGameEngine } from './TowerGameEngine';
export { MechanicEffectEngine } from './MechanicEffectEngine';
export type { MechanicState, MechanicEffectResult } from './MechanicEffectEngine';
export { ZoneEffectResolver } from './ZoneEffectResolver';
export type { ZoneEffectResult } from './ZoneEffectResolver';
