export const MOVEMENT_CONFIG = {
  DICE_SIDES: 6,
  MIN_DICE_VALUE: 1,
  MAX_DICE_VALUE: 6,
  MAX_REACHABLE_DISTANCE: 10,
  MOVE_ANIMATION_DURATION_MS: 500,
  DICE_ROLL_ANIMATION_MS: 800,
  ALLOW_UNDO: false,
  FORCE_MOVE_ANIMATION_MS: 300,
} as const;
