export const REWARD_CONFIG = {
  DATA_PACKET_SELECT_COUNT: 3,
  DATA_PACKET_PER_LAYER: 9,
  BOOKSTORE_OFFER_COUNT: 3,
  SKILL_MAX_ACTIVE_SLOTS: 3,
  SKILL_INVENTORY_UNLIMITED: true,
  DATA_PACKET_MAX_OWNED: 999,
} as const;
